### ISSUE TITLE
Can you Include SSH Options for a Key?

### ISSUE THREAD

**Issue by mrclausen** [Q-Technologies/puppet-local_users#4]
First off, brilliant module.... there are a lot of account modules (including the one from Puppet Labs)  on Puppet Forge, but none of them really work well with Hiera. 

That being said, is it possible to pass SSH options into the module as part of the local_users::add::keys: hash?

**Comment by mattqm** [comment]
Hi @mrclausen, thanks for the kind words.  When you say SSH options, do you mean populating `~/.ssh/config`?

**Comment by mrclausen** [comment]
No, these would be the options that can be included in an authorized_keys file at the very start of an entry (i.e. from="XXXXX", no-pty, no-agent-forwarding, etc.

**Comment by mattqm** [comment]
I've implemented a pass through of 'options' and 'target' for ssh_authorized_key, so you should be able to just specify then as additional fields in the local_users::add::keys: hashes.  It's in as commit bc986cc32c08a6ea9ded432aae6a9025f016321e.  It passes PDK validation, but I have not tested.  Do you want to try it out?

**Comment by mattqm** [comment]
You'll need to use 6b40103faa27d6d7845df4e4af2d5bb232bf6c4c as I had to fix something unrelated.

**Comment by mrclausen** [comment]
Hi Matt, I tried it this morning but the compile blew up on the client:

Error: Could not retrieve catalog from remote server: Error 500 on SERVER: Server Error: Evaluation Error: Error while evaluating a Resource Statement, Class[Local_users::Add]:
  expects a value for parameter 'purge_ssh_keys'
  expects a value for parameter 'group_auth_membership'
  expects a value for parameter 'system_group'
  expects a value for parameter 'user_group_membership' (file: /etc/puppetlabs/code/environments/sandbox/modules/local_users/manifests/init.pp, line: 7, column: 6) on node XXXXXXXXX

**Comment by mattqm** [comment]
Hmmm, that's really puzzling.  That would only happen if it is not finding the internal module hiera.  Has it worked previously for you?  What version of Puppet are you using?  Also, how did you deploy the module to the master and how are you invoking it?  Probably worth posting some heira that demonstrates the problem.

The module is still working for me - though I have not tested authorized keys options.

**Comment by mrclausen** [comment]
Yeah, I'm using the version off of Puppet Forge (v1.3.0) and I had just replaced only the add.pp manifest (it was the only change that GitHub was showing. This is on a Puppet Server v6.3.0 with a Puppet Client v6.4.0 pulling the configuration down.

Here's how I have the Hiera configured for local_user within the site:

<PRE>local_users::add::keys:
   -
      comment: 'root@someserver.com'
      type: ssh-rsa
      key: 'SSH KEY HERE'
      options: 'from="10.X.X.X"'
   -
      comment: 'root@someotherserver.com'
      type: ssh-dss
      key: 'YET ANOTHER SSH KEY'
   -
      comment: 'user@assetserver.com'
      type: ssh-rsa
      key: 'ASSET MANAGEMENT SSH KEY'

local_users::clear_auth_keys::username: 'root'
local_users::clear_auth_keys::username: 'assetuser'

local_users::add::groups:
   assetuser:
      gid: 12345

local_users::add::users:
   root:
      mode: '0700'
      auth_keys:
         - 'root@someserver.com'
         - 'root@someotherserver.com'
   snoadmin:
      uid: '12345'
      gid: '12345'
      comment: 'Asset Management User'
      mode: '0750'
      auth_keys:
         - 'user@assetserver.com'</PRE>

**Comment by mattqm** [comment]
There are quite some major changes between the that commit and 1.3.0 - so that will be the reason.  Anyway, I've decided to release a new version 1.3.2 as I'm pretty confident it is stable as the features I'm currently using are working fine.  Try that version out and we can work from there.

**Comment by mrclausen** [comment]
So I pulled down v1.3.2 from Puppet Forge and it's all working correctly now (including the addition of the options field for the authorized_keys file).   So thanks a lot for adding that in! :-)

**Comment by mattqm** [comment]
Glad to hear!  I'll close this off.  Cheers.
